- README.md
- rocketmq_exporter_overview.json
- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
- src/main/java/org/apache/rocketmq/exporter/util/Mix.java
What is the purpose of the change
add grafana dashboard for rocketmq exporter and makes the some metrics have fixed precison
Brief changelog
add grafana dashboard and Modify some metrics
Verifying this change
Follow this checklist to help us incorporate your contribution quickly and easily. Notice, it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR.
Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
Format the pull request title like [ISSUE #123] Fix UnknownException when host config …
> [ISSUE #1]Add grafana dashboard for rocketmq exporter and Modify some metrics

- .travis.yaml
- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
Fix code style issue to avoid build error and add travis CI
XX
XXXX
> [ISSUE #38] Fix code style issue to avoid build error and add travis CI

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
issue #36 
broker stats still report old metrics data on dledger mode
XXXX
> [ISSUE #36]Fix broker stats still report old metrics data on dledger mode

- src/main/java/org/apache/rocketmq/exporter/config/RMQConfigure.java
- src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminExtImpl.java
- src/main/java/org/apache/rocketmq/exporter/service/client/MQAdminInstance.java
- src/main/resources/application.yml
Make RocketMQ-Exporter compatible with RocketMQ 4.8.0
Make RocketMQ-Exporter compatible with RocketMQ 4.8.0
XXXX
> [ISSUE #45] Make RocketMQ-Exporter compatible with RocketMQ 4.8.0

- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
issue #53 
When messageModel() return null, use the default value.
XXXX
> [ISSUE #53] Fix npe when messageModel return null

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
> fix brokerRuntimePutMessageSizeTotal val

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
- src/main/java/org/apache/rocketmq/exporter/config/RMQConfigure.java
- src/main/java/org/apache/rocketmq/exporter/service/impl/RMQMetricsServiceImpl.java
- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
- src/main/resources/application.yml
#64 
By analyzing the heap dump file, it is found that there are two reasons for OOM:
1. The life cycle of the HashMap used to collect metrics runs through the program and cannot be GC.
2. The program did not delete out-of-date metrics, resulting in the amount of data in HashMap only increasing.
To solve this problem. Use Google Guava Cache data structure to replace ConcurrentHashMap.Because Cache can be set to automatically delete out-of-date content. In order to adapt to the general situation,we make the out-of-date time configurable.
1. We compared the heap dump files of the original program and the optimized program,as follows:
We can find that the origin program will accumulate a large number of HashMap instances.Over time, it will cause OOM.
Through these two picture, we can find …
> fix rocketmq-exporter causes OOM Error

- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
delete the unused import in MetricsCollectTask.java
#72
> fix the error when building the project 

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
> [ISSUE #83] make exporter collect right putMessageSizeTotal for broker

- src/main/java/org/apache/rocketmq/exporter/model/BrokerRuntimeStats.java
- src/main/java/org/apache/rocketmq/exporter/util/Utils.java
- src/test/java/org/apache/rocketmq/exporter/util/UtilsTest.java
> [ISSUE #86] Convert humanReadable to machineReadable for commitLogDirCapacity

- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
- src/main/resources/logback.xml
#77
remove unnecessary warning logs
remove unnecessary warning logs
> remove unnecessary warning logs

- src/main/java/org/apache/rocketmq/exporter/model/metrics/ConsumerTopicDiffMetric.java
> [ISSUE #95] hashCode() and equats() should calculate all fields

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
- src/main/java/org/apache/rocketmq/exporter/model/BrokerRuntimeStats.java
Issue https://github.com/apache/rocketmq/issues/3859
add metric: `rocketmq_brokeruntime_put_latency_99` & `rocketmq_brokeruntime_put_latency_999` 
P99
P999
> Add metric: putLatency99 & putLatency999

- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
close #110 
several metrics not correct
metrics bugfix: switch getTps() to getSum()
> [ISSUE #110] metrics bugfix: switch getTps() to getSum()

- README.md
1. fix some outdated info in README.md
close: https://github.com/apache/rocketmq-exporter/issues/133
XXXXX
XX
XXXX
> [ISSUE #133]: fix some outdated info in README.md

- pom.xml
- src/main/resources/application.yml
fix #135 
1. upgrade to spring boot 2.7.11 
2. add junit dependency since spring boot 2.7.11 not contain it
3. temporary solve MetricsCollectTask dependency cycle
XXXX
> [ISSUE #135] Upgrade to jackson-databind 2.13.5, fix high vulnerabilities

- src/main/docker/Dockerfile
- src/main/java/org/apache/rocketmq/exporter/model/BrokerRuntimeStats.java
This reverts commit fc42cf77b585a91f7d0ec713677da30242a0dc38.
fix some problems from #113 
fix #131, fix #127, fix #117, fix #115
XX
XXXX
> fix some errors which make exporter can't run

- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
This reverts commit 767612c1958ba8cbb29cfb734132878b71e9185b.
revert #108
fix #128, fix #123, fix #121, fix #114
XX
XXXX
> Revert "metrics bugfix: switch getTps() to getSum()"

- pom.xml
- src/main/docker/Dockerfile
fix #154
fix the name of jar file in configurations of docker-maven-plugin.
XXXX
> [ISSUE #154] make building docker images successful

- pom.xml
Add scm configuration for releasing.
XX
XXXX
> [ISSUE #153] add scm block for release

- pom.xml
> [ISSUE #160] modify groupId and other configurations

- pom.xml
Merge the pre-release branch into master
> [ISSUE #153] Merge the pre-release branch into master

- README.md
SkyWalking accepted the RocketMQ monitoring as a native bundled dashboard. Add relative links here.
Link and intro to the SkyWalking docs.
No code change. Features are verified and maintained by SkyWalking community. FYI @peachisai 
> Add SkyWalking dashboard

- src/main/java/org/apache/rocketmq/exporter/collector/RMQMetricsCollector.java
- src/main/java/org/apache/rocketmq/exporter/task/MetricsCollectTask.java
Add mtric: rocketmq_broker_commitlog_diff (The synchronization behind message size between master and slave.)
XXXX
> add metric:rocketmq_broker_commitlog_diff

- README.md
- rocketmq_exporter.json
[#93](https://github.com/apache/rocketmq-exporter/issues/93)
XX
XXXX
> [ISSUE #93]Optimize the grafana dashboard.
